### ISSUE TITLE
Add option in List Swap code to retain a user selected amount

### ISSUE THREAD

**Issue by bryancasler** [4site-interactive-studios/engrid-scripts#132]
Our "List Swap" code developed for AIUSA allows via custom code for the page editor to define One-time / Monthly giving frequencies and their associated default amount. When done this way, as a user switches between One-time and Monthly options, no matter what they had previously selected or entered into the Other Amount field, the value selected will be switched back to the default.

We should expand this so that on the code block an option can be set that allows for this behavior of selecting the default amount to be turned off if the user at any point has selected a non-default amount or entered a custom amount. This way the defaults change as you swap back and forth frequencies until you select or enter your own amount, then this choice is respected and the defaults do not change at all.

Example Page: https://donate.amnestyusa.org/page/81997/donate/1?mode=DEMO

Example of Existing Code
```
<script>
window.EngridAmounts = {
    onetime: {
        amounts: {
            "$250": 250,
            "$100": 100,
            "$50": 50,
            "$35": 35,
            "Other": "other"
        },
        default: 100
    },
    monthly: {
        amounts: {
          "$50": 50,
          "$30": 30,
          "$25": 25,
          "$15": 15,
          "Other": "other"
        },
        default: 30
    }
}
</script>
```

Example of New Code with "keepUserAmount"
```
<script>
window.EngridAmounts = {
   keepUserAmount,
    onetime: {
        amounts: {
            "$250": 250,
            "$100": 100,
            "$50": 50,
            "$35": 35,
            "Other": "other"
        },
        default: 100
    },
    monthly: {
        amounts: {
          "$50": 50,
          "$30": 30,
          "$25": 25,
          "$15": 15,
          "Other": "other"
        },
        default: 30
    }
}
</script>
```

**Comment by fernanDOTdo** [comment]
@bryancasler 
﻿ I've done this automatically:

When you're using the `window.EngridAmounts` option, the user-selected amount will persist when changing frequencies if:

1. We're coming from a backend error.
2. We have an amount defined via URL.
3. The user selected a non-default amount.

Let me know if you need more!

Fernando

**Comment by bryancasler** [comment]
This is great! Please add details to the ENgrid 2023 Documentation

https://docs.google.com/document/d/1zF-86Iq8tCRk4HCv-JaJYZulkC273x-_QODUed9F0Pw/edit
