### ISSUE TITLE
Our checks for gift recurrancy doesn't trigger when gift recurrancy is populated because of URL arguments

### ISSUE THREAD

**Issue by bryancasler** [4site-interactive-studios/engrid-scripts#141]
If you have a page with a one-time donation by default and then you add "&transaction.recurrpay=Y" to the URL, this causes the page to load with Monthly (or similar) selected.

In this instance, on page load, the Donation Amount buttons don't get their "/mo" appended, the $FREQUENCY on the submit button doesn't update to "Monthly". and on the <body> data-engrid-transaction-recurring-frequency="onetime".

**Comment by fernanDOTdo** [comment]
Hey, @bryancasler !

This is actually working if you pass all the necessary values to make a Donation Monthly. See:

AIUSA: https://donate.amnestyusa.org/page/81997/donate/1?mode=DEMO&transaction.recurrpay=Y&transaction.recurrfreq=MONTHLY
OC: https://donate.oceanconservancy.org/page/92465/donate/1?transaction.recurrpay=Y&transaction.recurrfreq=MONTHLY

The `transaction.recurrpay=Y` is not enough to change a Donation to Monthly.

Is there something you want us to do about that?
