### ISSUE TITLE
Refine function for adding markup to the dom with Javascript

### ISSUE THREAD

**Issue by bryancasler** [4site-interactive-studios/engrid-scripts#78]
Sometimes we want to create markup and inject it into the DOM at a specific place. Every time we do that, we have to reinvent the wheel for doing it. The idea here would be to create a function that help facilitate those needs. Something like the following where raw HTML contains the markup to be placed.

`function injectHTML(rawHTML, '#cvv label', beforeend);`

Fernando said

```
addComponent(component) {
    // Add the container on the right position
    if (!!this.options.position) {
      let field_base = document.querySelector(this.options.position);
      if (!field_base) {
        return false;
      }
      field_base.parentNode.insertBefore(component, field_base.nextSibling);
    } else {
      let field_base = document
        .querySelector(".en__submit")
        .closest(".en__component");
      field_base.parentNode.insertBefore(component, field_base);
    }
  }
```

I just need to talk about it for 3 minutes and that’s all. Because I think this part is unnecessary:
'beforebegin': Before the element itself.
'afterbegin': Just inside the element, before its first child.
'beforeend': Just inside the element, after its last child.
'afterend': After the element itself.

Ref
- https://medium.com/@tforward/get-html-to-the-dom-fast-with-js-template-literals-insertadjacenthtml-24b8aa4e8807
- https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML

**Comment by fernanDOTdo** [comment]
@bryancasler I went to our discussion about this from March 17, 2021. Then I researched the issue and created a modern solution, which is implemented as static functions for the Engrid class:

**addHtml(html, target, position)
removeHtml(target)**

For the `addHtml` function, the `html` parameter can be either a string (example: `<strong>Fernando</strong>`) or an Element.
The `target` should be a string for query selector (example: `body` , or `.en__submit`).
The `position` defaults to "`before`", but can be set as "`after`".
Combining only those 2 positions with the `target` element, you can add your component anywhere you want in the page.

The `removeHtml` function expects a string for query selector (example: `body` , or `.en__submit`).

It's committed here: https://github.com/4site-interactive-studios/engrid-scripts/commit/1d331dc2c9ebb31487df7fa5305e1dc096b5b9c0

It will be available on the next ENgrid-Scripts version.
Now we can make use of those functions on any component we want, or in the client theme customizations.

Let me know if you have questions!
